services:
  register:
    image: lw89233/register:latest
    container_name: register-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${REGISTRATION_MICROSERVICE_PORT}:${REGISTRATION_MICROSERVICE_PORT}"